#!/bin/sh
#/etc/init.d/pycaster

export PATH=$PATH:/usr/local/bin
export NODE_PATH=$NODE_PATH:/usr/local/lib/node_modules

case "$1" in
  start)
  exec forever start --sourceDir=/home/pi/PYCASTER server.js
  ;;
stop)
  exec forever stop --sourceDir=/home/pi/PYCASTER server.js
  ;;
*)
  echo "Usage: /etc/init.d/pycaster {start|stop}"
  exit 1
  ;;
esac

exit 0
